use_frameworks!

platform :ios, '9.0'

target 'zxgTool_Example' do
  pod 'zxgTool', :path => '../'

  target 'zxgTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
